name: Kuro BETA Monitor 11:30

on:
  schedule:
    - cron: "30 4 * * *"   # 11:30 ไทย
  workflow_dispatch:

jobs:
  beta-monitor:
    name: Run BETA Monitor 11:30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests


      - name: Run BETA scripts
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
          WEBHOOK1: ${{ secrets.WEBHOOK1 }}
          WEBHOOK2: ${{ secrets.WEBHOOK2 }}
          WEBHOOK3: ${{ secrets.WEBHOOK3 }}
          WEBHOOK4: ${{ secrets.WEBHOOK4 }}
          WEBHOOK5: ${{ secrets.WEBHOOK5 }}
        run: |
          python "Banner/鸣潮 BETA.py"
          python "Banner/Wuthering Waves BETA.py"

      - name: Commit and Push BETA logs
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          mkdir -p Kuro/log

          git add Kuro/log

          if ! git diff --cached --quiet; then
            git commit -m "Update logs [skip ci]"
            git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:Webhook
          else
            echo "No changes to commit"
          fi
