name: Kuro PROD Monitor 12:00

on:
  schedule:
    - cron: "0 5 * * *"   # 12:00 ไทย
  workflow_dispatch:

jobs:
  prod-monitor:
    name: Run Monitor 12:00
    runs-on: ubuntu-latest

    steps:
      # =====================================================
      # Checkout
      # =====================================================

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # =====================================================
      # Python
      # =====================================================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # =====================================================
      # Install
      # =====================================================

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -U discord.py

      # =====================================================
      # Wuthering Waves EN
      # =====================================================

      - name: Run Wuthering Waves
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_1 }}
        run: |
          python "Kuro Game/Wuthering Waves.py"
          python "Kuro Game/鸣潮.py"
          
          python "Kuro Game/Punishing Gray Raven.py"
          python "Kuro Game/战双帕弥什.py"

      # =====================================================
      # Commit Logs
      # =====================================================

      - name: Commit and Push logs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          mkdir -p Kuro/log

          git add Kuro/log

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update logs [skip ci]"

          git pull --rebase origin Webhook
          git push origin HEAD:Webhook