name: Kuro Game Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # ทุก 5 นาที
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run all game monitors
        env:
          KuroWEBHOOK1: ${{ secrets.WEBHOOK1 }}
          KuroWEBHOOK2: ${{ secrets.WEBHOOK2 }}
          KuroWEBHOOK3: ${{ secrets.WEBHOOK3 }}

        run: |
          python API/GI.py
          python API/HI3.py
          python API/HSR.py
          python API/ZZZ.py
          python API/HNA.py
